default_connection_name = "SF_Dinesh2012"

[SF_Dinesh2012]
account = "GQB91797"
user = "dinesh2012"
password = "Din143@doc1"
database = "CORTEX_ANALYST_DEMO"
schema = "REVENUE_TIMESERIES"
warehouse = "CORTEX_ANALYST_WH"
role = "ACCOUNTADMIN"
host = "gqb91797.snowflakecomputing.com"
stage = "RAW_DATA"
file = "revenue_timeseries.yaml"
